# Generated by Django 5.2.17 on 2026-08-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_per_minute_watched', models.PositiveIntegerField(default=10, help_text='XP awarded per 1 minute of video watched')),
                ('xp_for_completing_task', models.PositiveIntegerField(default=50, help_text='Bonus XP awarded upon completing a video task')),
                ('xp_for_daily_streak', models.PositiveIntegerField(default=15, help_text='XP awarded for claiming daily login streak reward')),
                ('xp_for_daily_spin', models.PositiveIntegerField(default=15, help_text='XP awarded for completing daily spin wheel')),
                ('xp_for_referral', models.PositiveIntegerField(default=100, help_text='XP awarded for referring a new active user')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'XP Settings',
                'verbose_name_plural': 'XP Settings',
            },
        ),
    ]
