# Generated by Django 5.2.17 on 2026-08-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFraudProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.FloatField(default=0.0, help_text='Calculated fraud score from 0.0 (clean) to 1.0 (malicious).')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for manual admin audit.')),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('last_known_ip_hash', models.CharField(blank=True, max_length=64)),
                ('suspicious_pings_count', models.IntegerField(default=0)),
                ('total_pings_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Fraud Profile',
                'verbose_name_plural': 'User Fraud Profiles',
            },
        ),
    ]
