# Generated by Django 5.1.15 on 2026-08-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter')], default='gemini', help_text='Active LLM provider for generating video keywords.', max_length=20)),
                ('gemini_api_key', models.CharField(blank=True, help_text='Google Gemini API Key (or set GEMINI_API_KEY environment variable).', max_length=255)),
                ('openrouter_api_key', models.CharField(blank=True, help_text='OpenRouter API Key (or set OPENROUTER_API_KEY environment variable).', max_length=255)),
                ('selected_model', models.CharField(blank=True, help_text='Dynamic Model ID chosen from the live provider model list (e.g. gemini-2.5-flash or meta-llama/llama-3.3-70b-instruct).', max_length=150)),
                ('custom_system_prompt', models.TextField(blank=True, default='You are a YouTube search expert.\nGiven the YouTube video\'s title, channel, and description, generate 6 to 10 natural, highly-relevant search query phrases that real viewers would type into the YouTube search bar to find this exact video.\n\nRules:\n1. Every query must be a complete, realistic search term (e.g. "Flutter in 100 seconds Fireship", "Never Gonna Give You Up official video Rick Astley").\n2. Queries must be specific enough so the video ranks at or near the top of YouTube search results.\n3. Include title-focused queries, channel-focused queries, and topic/question queries.\n4. Do NOT output numbered lists, markdown explanations, or preamble. Return ONLY a valid JSON array of strings: ["phrase 1", "phrase 2", "phrase 3", ...]\n', help_text='Prompt instructions sent to the LLM for keyword extraction.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable AI keyword generation.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Keyword Settings',
                'verbose_name_plural': 'AI Keyword Settings',
            },
        ),
    ]
