# Generated by Django 5.2.17 on 2026-08-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='active_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter')], default='openrouter', help_text='Active LLM provider for generating video keywords.', max_length=20),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='custom_system_prompt',
            field=models.TextField(blank=True, default='You are a YouTube SEO and Search Retrieval Specialist.\n\nWhen provided a YouTube video URL, title, channel name, and metadata details, analyze the video\'s title, creator name, description, visual cues, unique tools/workflows, and core topic.\n\nGenerate exactly 8 high-precision YouTube search queries that will rank this specific video on the first page (#1 to #3) of YouTube search results.\n\nCategorize and format the queries as follows:\n1. [Channel Name] + [Core Topic] (Exact creator lookup)\n2. [Exact Title Match] (Full video title)\n3. [Core Topic] + [Channel Name] (Topical variant)\n4. [Specific Tools / Software Mentioned] + [Core Topic] (Toolchain search)\n5. [Exact Hook Phrase / Unique Catchphrase] (Verbatim spoken or thumbnail text)\n6. [Broad Tutorial Query] + [Channel Name] (Educational intent)\n7. [Niche / Case Study Topic] + [Channel Name] (Specific example used in video)\n8. [High-Intent User Problem / Solution Query] (Natural conversational search)\n\nUnder each search query, include a 1-sentence note in parentheses explaining why that query guarantees a top-ranking match.\n\nOutput format: Return ONLY a valid JSON array of 8 objects with "category", "query", and "note" keys:\n[\n  {\n    "category": "1. Exact creator lookup",\n    "query": "...",\n    "note": "..."\n  },\n  ...\n]\n', help_text='Prompt instructions sent to the LLM for keyword extraction.'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='selected_model',
            field=models.CharField(blank=True, help_text='Dynamic Model ID chosen from the live provider model list (e.g. google/gemini-2.5-flash or meta-llama/llama-3.3-70b-instruct).', max_length=150),
        ),
    ]
