# Generated by Django 5.2.17 on 2026-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(db_index=True, default='watch_reward', max_length=30),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='wallet_wall_created_929d33_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_wall_transac_2c0a43_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx'),
        ),
    ]
