# Generated by Django 5.1.15 on 2026-08-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('reward_type', models.CharField(choices=[('per_time', 'Per Time'), ('watch_all', 'Watch All'), ('target', 'Target')], default='per_time', max_length=20)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.FloatField(default=0.0)),
                ('total_watched_seconds', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to=settings.AUTH_USER_MODEL)),
                ('video_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.videotask')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video_task')},
            },
        ),
    ]
