# Generated by Django 5.2.17 on 2026-08-22 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videotask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotask',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['last_watched_at', 'is_completed'], name='tasks_watch_last_wa_053e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['user', 'last_watched_at'], name='tasks_watch_user_id_5ec914_idx'),
        ),
    ]
