# Generated by Django 5.2.17 on 2026-08-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('watch', 'Watch & Retention'), ('social', 'Social & Referral'), ('earning', 'Earning & Economy'), ('special', 'Special & Milestones')], default='watch', max_length=30)),
                ('icon_url', models.URLField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('target_bronze', models.FloatField(default=1.0)),
                ('target_silver', models.FloatField(default=5.0)),
                ('target_gold', models.FloatField(default=25.0)),
                ('target_diamond', models.FloatField(default=100.0)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_count', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_claimed_date', models.DateField(blank=True, null=True)),
                ('freeze_used_this_week', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('xp', models.BigIntegerField(db_index=True, default=0)),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('streak_freeze_count', models.IntegerField(default=0)),
                ('showcase_badges', models.JSONField(blank=True, default=list)),
                ('lifetime_coins_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_watch_seconds', models.FloatField(default=0.0)),
                ('tasks_completed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('quest_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('target_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=0)),
                ('coin_reward', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('xp_reward', models.IntegerField(default=25)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'difficulty'],
                'unique_together': {('user', 'date', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='ScratchCardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('grid_panels', models.JSONField(default=list)),
                ('prize_type', models.CharField(max_length=50)),
                ('prize_value', models.CharField(max_length=50)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SpinWheelClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('prize_type', models.CharField(max_length=50)),
                ('prize_value', models.CharField(max_length=50)),
                ('segment_landed', models.IntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('none', 'Locked'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond'), ('legendary', 'Legendary')], default='none', max_length=20)),
                ('progress_current', models.FloatField(default=0.0)),
                ('progress_target', models.FloatField(default=1.0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
