# Generated by Django 5.2.17 on 2026-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1_coins', models.PositiveIntegerField(default=5, help_text='Coins awarded for Day 1')),
                ('day_2_coins', models.PositiveIntegerField(default=10, help_text='Coins awarded for Day 2')),
                ('day_3_coins', models.PositiveIntegerField(default=15, help_text='Coins awarded for Day 3')),
                ('day_4_coins', models.PositiveIntegerField(default=20, help_text='Coins awarded for Day 4')),
                ('day_5_coins', models.PositiveIntegerField(default=30, help_text='Coins awarded for Day 5')),
                ('day_6_coins', models.PositiveIntegerField(default=40, help_text='Coins awarded for Day 6')),
                ('day_7_coins', models.PositiveIntegerField(default=50, help_text='Coins awarded for Day 7')),
                ('mystery_box_day', models.PositiveIntegerField(default=7, help_text='Day that triggers mystery box reward')),
                ('streak_reset_days', models.PositiveIntegerField(default=1, help_text='Threshold of missed days before streak resets to Day 1')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Streak Settings',
                'verbose_name_plural': 'Streak Settings',
            },
        ),
    ]
