# Generated by Django 5.2.17 on 2026-08-23 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_streaksettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label on wheel segment, e.g. '50 Coins'", max_length=100)),
                ('reward_coins', models.PositiveIntegerField(default=10, help_text='Number of coins awarded when landed')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Probability weight percentage (1-100)')),
                ('color', models.CharField(default='#6366F1', help_text='Hex color code for wheel segment UI', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment is active on the wheel')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on wheel (1-12)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spin Wheel Segment',
                'verbose_name_plural': 'Spin Wheel Segments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailySpinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('coins_won', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spin_records', to=settings.AUTH_USER_MODEL)),
                ('segment_won', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_wins', to='gamification.spinwheelsegment')),
            ],
            options={
                'verbose_name': 'Daily Spin Record',
                'verbose_name_plural': 'Daily Spin Records',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'spin_date')},
            },
        ),
    ]
