# Generated by Django 5.2.17 on 2026-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_spinwheelsegment_dailyspinrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpinWheelClaim',
        ),
    ]
